python3-jupyter-packaging: Upgrade to 0.12.0 version
In Langdale release python3-jupyter-packaging_0.10.6 fails to
build dependency packages such as python3-jupyterlab-pygments,
python3-jupyterlab-widgets, python3-widgetsnbextension with below
errors.

Log data follows:
| DEBUG: Executing shell function do_compile
| Traceback (most recent call last):
|   File "/scratch/sandeepg/yocto/2023.1/build-jupyter-kr260-tmp/work/cortexa72-cortexa53-xilinx-linux/python3-jupyterlab-pygments/0.2.2-r0/jupyterlab_pygments-0.2.2/setup.py", line 8, in <module>
|     from jupyter_packaging import (
|   File "/scratch/sandeepg/yocto/2023.1/build-jupyter-kr260-tmp/work/cortexa72-cortexa53-xilinx-linux/python3-jupyterlab-pygments/0.2.2-r0/recipe-sysroot-native/usr/lib/python3.10/site-packages/jupyter_packaging/__init__.py", line 6, in <module>
|     from .setupbase import *
|   File "/scratch/sandeepg/yocto/2023.1/build-jupyter-kr260-tmp/work/cortexa72-cortexa53-xilinx-linux/python3-jupyterlab-pygments/0.2.2-r0/recipe-sysroot-native/usr/lib/python3.10/site-packages/jupyter_packaging/setupbase.py", line 37, in <module>
|     from setuptools.config import StaticModule
| ImportError: cannot import name 'StaticModule' from 'setuptools.config'

This is due to using setuptools version 61 and above. This issue is
fixed in python3-jupyter-packaging 0.12.0 version hence upgrade
python3-jupyter-packaging version from 0.10.6 to 0.12.0.

Signed-off-by: Sandeep Gundlupet Raju <sandeep.gundlupet-raju@amd.com>